### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by Dirowa** [galaxyproject/ptdk#16]
When I try to generate a skeleton for a new galaxy tutorial it gives the following error:

```
Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
```

All parameters were filled in.
Galaxy instance chosen is ```usegalaxy.eu```

**Comment by hexylena** [comment]
I'm sorry I missed this @Dirowa (feel free to ping me in person as well).  We were experiencing timeouts for a period, but it might be better now.

**Comment by hexylena** [comment]
Closed pending further response from submitter.
