### ISSUE TITLE
Error 403 when generating a skeleton from my workflow

### ISSUE THREAD

**Issue by nakucher** [galaxyproject/ptdk#23]
<img width="1385" alt="Screen Shot 2023-07-11 at 2 41 25 PM" src="https://github.com/galaxyproject/ptdk/assets/80000074/819de0f8-8100-4732-ab33-0dd887eec853">
For these inputs, I get this error.

folder name: sars-with-galaxy-on-anvil
tutorial name: SARS-CoV-2 Viral Sample Alignment and Variant Visualization
galaxy instance: usegalaxy.org
workflow id: c9a8fd89224e7414

Error: GET: error 403: b'{"err_msg": "Provided API key is not valid.", "err_code": 403001}', 0 attempts left: {"err_msg": "Provided API key is not valid.", "err_code": 403001}

**Comment by hexylena** [comment]
Ahhh ok, something must've happened to our .org API key. Hmm.

**Comment by hexylena** [comment]
I've pinged @natefoo out of band to help with that, since I only have an API key for that account, not any more information

**Comment by hexylena** [comment]
It is now fixed
